// Generates src/styles/generated/content-classes.txt, a Tailwind safelist for classes that
// only exist in the database (article HTML and interactive-component scripts) and so are
// invisible to Tailwind's file scanner. Sources:
//   1. utility-looking tokens in every markdown/scripts field (read-only DB scan)
//   2. class names built at runtime from the postInteractiveElements.js color constants,
//      e.g. `bg-${ielightbgclass}` → bg-gray-100
//   3. every class selector of the legacy compiled stylesheet, so nothing an article could
//      rely on disappears in the rewrite
//
//   MONGODB_URI=mongodb://127.0.0.1:27017/qed npm run extract:classes
import fs from "node:fs";
import path from "node:path";
import mongoose from "mongoose";
import { config } from "../src/lib/config";

const PREFIXES = new Set(
    (
        "bg text border rounded p px py pt pb pl pr ps pe m mx my mt mb ml mr ms me w h min max size flex grid gap space " +
        "items justify self place content font leading tracking shadow ring opacity z top left right bottom inset " +
        "overflow object aspect transition duration ease delay animate transform translate rotate scale skew origin " +
        "cursor pointer select resize outline fill stroke decoration underline list whitespace break col row order " +
        "divide from via to backdrop blur drop filter sr not prose container table align shrink grow basis line " +
        "hyphens indent invert hidden block inline relative absolute fixed sticky static italic uppercase lowercase " +
        "capitalize truncate visible invisible contents isolate mix accent caret columns float clear box"
    ).split(" ")
);

const VARIANT = /^(?:(?:sm|md|lg|xl|2xl|mobile|dark|hover|focus|active|group-hover|first|last|odd|even|disabled|motion-safe|motion-reduce|not-prose|prose-[a-z]+)[:])*/;

function isUtility(token: string): boolean {
    if (token.length > 60 || !/^[!-]?[a-z0-9:[\]#%./_-]+$/i.test(token)) return false;
    const base = token.replace(VARIANT, "").replace(/^[!-]/, "");
    const head = base.split(/[-[]/)[0];
    return PREFIXES.has(head);
}

// Values of the color constants in public/js/postInteractiveElements.js.
const RUNTIME_COLORS = [
    "ie-light-bg",
    "ie-light-main",
    "ie-light-contrast",
    "ie-dark-bg",
    "ie-dark-main",
    "ie-dark-contrast",
    // v1 values, in case an article hardcoded them
    "gray-100",
    "gray-300",
    "blue-600",
    "gray-700",
    "gray-500",
    "blue-200"
];
const COLOR_UTILITIES = ["bg", "text", "border", "ring", "fill", "stroke", "outline", "divide", "from", "via", "to", "decoration", "accent", "caret", "placeholder", "shadow"];
const COLOR_VARIANTS = ["", "dark:", "hover:", "dark:hover:", "focus:", "dark:focus:"];

function legacyStylesheetClasses(): string[] {
    const css = fs.readFileSync(path.resolve("tests/legacy/styles.legacy.css"), "utf8");
    const classes = new Set<string>();
    for (const match of css.matchAll(/\.((?:\\.|[a-zA-Z0-9_-])+)/g)) {
        const name = match[1].replace(/\\(.)/g, "$1");
        if (isUtility(name)) classes.add(name);
    }
    return [...classes];
}

async function databaseClasses(): Promise<string[]> {
    await mongoose.connect(config.mongodbUri, { serverSelectionTimeoutMS: 5000 });
    const db = mongoose.connection.db!;
    const classes = new Set<string>();
    const collect = (value: unknown): void => {
        if (typeof value === "string") {
            for (const token of value.split(/[\s"'`<>=(){};,]+/)) if (isUtility(token)) classes.add(token);
        } else if (value && typeof value === "object") {
            Object.values(value).forEach(collect);
        }
    };
    for (const name of ["posts", "activities", "news", "magazines", "users"]) {
        for (const doc of await db.collection(name).find().toArray()) {
            collect([doc.content, doc.description, doc.about, doc.scripts]);
        }
    }
    await mongoose.disconnect();
    return [...classes];
}

async function main() {
    const runtime = COLOR_VARIANTS.flatMap((variant) =>
        COLOR_UTILITIES.flatMap((utility) => RUNTIME_COLORS.map((color) => `${variant}${utility}-${color}`))
    );
    const all = new Set([...legacyStylesheetClasses(), ...(await databaseClasses()), ...runtime]);
    const file = path.resolve("src/styles/generated/content-classes.txt");
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(
        file,
        "# Generated by scripts/extract-content-classes.ts. Do not edit.\n" + [...all].sort().join("\n") + "\n"
    );
    console.log(`Wrote ${all.size} classes to ${file}`);
}

main().catch((error) => {
    console.error(error);
    process.exit(1);
});
